#!/bin/bash

# Charger les variables d'environnement
source .env

# Créer un réseau pour Kafka
podman network create ${NETWORK_NAME}

# Démarrer le contrôleur Kafka (en mode KRaft)
podman run -d --name ${CONTROLLER_HOSTNAME} \
  --network=${NETWORK_NAME} \
  -e KAFKA_PROCESS_ROLES=controller \
  -e KAFKA_CONTROLLER_QUORUM_VOTERS=${CONTROLLER_ID}@${CONTROLLER_HOSTNAME}:${CONTROLLER_PORT} \
  -e KAFKA_NODE_ID=${CONTROLLER_ID} \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
  -e KAFKA_LISTENERS=CONTROLLER://${CONTROLLER_HOSTNAME}:${CONTROLLER_PORT},PLAINTEXT://0.0.0.0:9094 \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
  -e KAFKA_LOG_DIRS=${CONTROLLER_LOG_DIR} \
  -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
  -e KAFKA_KRAFT_MODE=true \
  -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
  -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
  -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 \
  -e KAFKA_LOG_RETENTION_MS=259200000 \
  ${KAFKA_IMAGE}

# Démarrer le broker Kafka
podman run -d --name ${BROKER_HOSTNAME} \
  --network=${NETWORK_NAME} \
  -e KAFKA_PROCESS_ROLES=broker \
  -e KAFKA_NODE_ID=${BROKER_ID} \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT \
  -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:${BROKER_PORT} \
  -e KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
  -e KAFKA_LOG_DIRS=${BROKER_LOG_DIR} \
  -e KAFKA_CONTROLLER_QUORUM_VOTERS=${CONTROLLER_ID}@${CONTROLLER_HOSTNAME}:${CONTROLLER_PORT} \
  -e KAFKA_KRAFT_MODE=true \
  -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
  -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
  -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 \
  -e KAFKA_LOG_RETENTION_MS=259200000 \
  ${KAFKA_IMAGE}
